---
server:
  port: 9999

logging:
  level:
    org:
      ap:
        dbdesign: TRACE

spring:
  application:
    name: apdbdesign
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    url: "jdbc:h2:mem:db;DB_CLOSE_DELAY=-1"
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  flyway:
    baseline-on-migrate: true
    enabled: true

  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB

info:
  app:
    name: "AP Comments DB Design"
    description: "Welcome to PAF"
    version: "1.0"

management:
  endpoints:
    web:
      exposure:
        include: health, info